# Generated by Django 5.1 on 2024-08-31 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0002_remove_categorymodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWatchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('watch_time', models.DurationField(blank=True, null=True)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netfiex_app.contentmodel')),
            ],
        ),
    ]
